/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Congreso;
import static Vista.UsaCongreso.losCongresos;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

/**
 *
 * @author fabian_esteban.lopez
 */
public class Page6 extends javax.swing.JPanel {

    /**
     * Creates new form Page1
     */
    public Page6() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();
        auxiliar = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setEnabled(false);
        bg.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Almacenar Archivo Texto");

        buscar.setText("ALMACENAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        auxiliar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(buscar)
                    .addComponent(auxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(676, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(buscar)
                .addGap(172, 172, 172)
                .addComponent(auxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1100, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        almacenarEnArchivoTexto();
    }//GEN-LAST:event_buscarActionPerformed
    public void almacenarEnArchivoTexto() {
        try {
            //Se define el archivo donde se almacenara la informacion de la coleccion
            String nombreArchivo = "datosCongreso.txt";
            PrintWriter salida = new PrintWriter(new BufferedWriter(new FileWriter(nombreArchivo)));

            //Se procesa la coleccion para extraer la informacion y almacenarla en archivo
            String linea = "";//Almacenara la informacion de cada linea del archivo.
            for (Congreso elem : losCongresos) {//entro a la coleccion y saco info
                linea = elem.getIdentificador() + "--" + elem.getNombre() + "--" + elem.getFechaYHoraInicio() + "--" + elem.getFechaYHoraTerminacion() + "--" + elem.getNombreOrganizador() + "--" + elem.getSuLugar().getNombreLugar() + "--" + elem.getSuLugar().getDireccion() + "--" + elem.getSuLugar().getCiudad();
                String lineaC = "--";
                if (elem.getSusInscripciones().size() != 0) {
                    for (int i = 0; i < elem.getSusInscripciones().size(); i++) {
                        //Conforma linea de salida de los cortes
                        lineaC += elem.getSusInscripciones().get(i).getNumero() + "," + elem.getSusInscripciones().get(i).getFechaYhora() + "," + elem.getSusInscripciones().get(i).getEstado() + ",";
                    }
                    linea += lineaC;
                }
                salida.println(linea);
            }//Fin for
    
              auxiliar.setText("Exito: almacenado correctamente.");
            salida.close();
            //Procesando cortes para agregar a la lista linea del archivo.

        } catch (IOException e) {

            auxiliar.setText("Error: no se pudo almacenar los datos en archivo texto.");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel auxiliar;
    private javax.swing.JPanel bg;
    private javax.swing.JButton buscar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
